// Auto-generated by convert_to_tflite.py
#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

extern const uint8_t g_model_data[];
extern const uint32_t g_model_data_len;

#endif // MODEL_DATA_H
